package meshService

const (
	UnknownTag MeshCommodityTag = "UNKNOWN"
)

var dataConstants = []string{
	"POINTS",
	"DISPLACEMENT",
	"SCALARS TEMPERATURE double",
	"SCALARS EQ_STRESS double",
	"EQ_STRAIN",
	"EQ_STR_RX",
	"NORMALSTRESS",
	"STRESSTENSOR_XX",
	"STRESSTENSOR_YY",
	"STRESSTENSOR_ZZ",
	"STRESSTENSOR_XY",
	"STRESSTENSOR_YZ",
	"STRESSTENSOR_XZ",
}

var dataConstantsName = []string{
	"POINTS",
	"DISPLACEMENT",
	"TEMPERATURE",
	"EQ_STRESS",
	"EQ_STRAIN",
	"EQ_STR_RX",
	"NORMALSTRESS",
	"STRESSTENSOR_XX",
	"STRESSTENSOR_YY",
	"STRESSTENSOR_ZZ",
	"STRESSTENSOR_XY",
	"STRESSTENSOR_YZ",
	"STRESSTENSOR_XZ",
}

var dataConstantsTagMap = map[string]MeshCommodityTag{
	"POINTS":          "POINTS",
	"DISPLACEMENT":    "DISPLACEMENT",
	"TEMPERATURE":     "TEMPERATURE",
	"EQ_STRESS":       "EQ_STRESS",
	"EQ_STRAIN":       "EQ_STRAIN",
	"EQ_STR_RX":       "EQ_STR_RX",
	"NORMALSTRESS":    "NORMALSTRESS",
	"STRESSTENSOR":    "STRESSTENSOR",
	"STRESSTENSOR_XX": "STRESSTENSOR",
	"STRESSTENSOR_YY": "STRESSTENSOR",
	"STRESSTENSOR_ZZ": "STRESSTENSOR",
	"STRESSTENSOR_XY": "STRESSTENSOR",
	"STRESSTENSOR_YZ": "STRESSTENSOR",
	"STRESSTENSOR_XZ": "STRESSTENSOR",
}
