export const REQUIRED_ENVS = [
  'KAFKA_BROKER',
  'KAFKA_CLIENT_ID',
  'KAFKAJS_NO_PARTITIONER_WARNING',
  'BLOB_STORAGE_ACCESS',
  'BLOB_STORAGE_SECRET',
  'BLOB_STORAGE_ENDPOINT',
  'BLOB_STORAGE_PORT',
  'DB_CONNECTION_STRING',
  'AUTH0_PORT',
  'AUTH0_ISSUER_URL',
  'AUTH0_AUDIENCE',
] as const;

export const BUCKET_DEFAUlT_NAME = 'mesh-vtk-files';
